sspanak/tt9

src/io/github/sspanak/tt9/ime/TraditionalT9.java

Fixed an incorrect settings reset on startup

---

src/io/github/sspanak/tt9/db/DictionaryDb.java
src/io/github/sspanak/tt9/db/DictionaryLoader.java
src/io/github/sspanak/tt9/db/WordsDao.java

This is to allow updating the frequencies without wiping out the dictionary. It will be useful when updating the dictionary after #124

Dictionary reloading is now upsert, not insert/ignore

---

src/io/github/sspanak/tt9/languages/Punctuation.java

There was previously no way to access the underscore - it is a necessary character for entering URLs, amongst other things
Added right behind the dash, though where it exists doesnt matter so much as THAT it exists as a choice

Add underscore to puncutation list

---

src/io/github/sspanak/tt9/ime/KeyPadHandler.java
src/io/github/sspanak/tt9/ime/TraditionalT9.java
src/io/github/sspanak/tt9/ime/modes/ModeDialer.java

FATAL EXCEPTION: main
Process: io.github.sspanak.tt9, PID: 13729
java.lang.NullPointerException: Attempt to invoke virtual method 'void io.github.sspanak.tt9.ime.helpers.TextField.setComposingText(java.lang.CharSequence)' on a null object reference
at io.github.sspanak.tt9.ime.TraditionalT9.clearSuggestions(TraditionalT9.java:476)
at io.github.sspanak.tt9.ime.TraditionalT9.onStop(TraditionalT9.java:190)
at io.github.sspanak.tt9.ime.TraditionalT9.onStart(TraditionalT9.java:161)
at io.github.sspanak.tt9.ime.KeyPadHandler.onStartInput(KeyPadHandler.java:81)
at io.github.sspanak.tt9.ime.TraditionalT9.onStartInput(TraditionalT9.java:27)
at android.inputmethodservice.InputMethodService.doStartInput(InputMethodService.java:1651)
at android.inputmethodservice.InputMethodService$InputMethodImpl.sta …

fix nullref on exiting dialer by long pressing of Back key on KYF33

---

src/io/github/sspanak/tt9/ime/modes/helpers/AutoTextCase.java

Lowercase is now enforced, when the cursor is next to or in the middle of a word.
Closes #267

Automatic text case improvement

---

src/io/github/sspanak/tt9/ime/TraditionalT9.java

Problem:
shouldBeOff() was called where it was unnecessary. shouldBeOff() is already called on onKeyUP, onKeyDown, and onKeyLongPress, so it is already handled before it would ever get to an Add word scenario.
Solution:
Remove call to shouldBeOff from inside showAddWord()

remove an unnecessary shouldBeOff() refernce

---

res/layout/main_numpad.xml
res/layout/main_small.xml

Problem:
XML attribute "fadingEdge" is applied to RecyclerView, however it is just being ignored:
<attr name="fadingEdge">
More info: https://developer.android.com/reference/android/R.attr.html#fadingEdge
Solution: 
Remove unused xml attribute

remove fadingEdge because it is deprecated

---

src/io/github/sspanak/tt9/TextTools.java

Problem:
while still typing a period in the middle of a sentence (such as wanting to type .com), the case of the C after the period was being suggested as a capital because it was treated as a new sentence. A new sentence does not begin after a period, but after the space after the period.
Solution:
Fixed regex which was fine with 0 instances of a space (/s), to have to include at least 1 space. This is allowing users to type .com naturally, instead of .Com

New Sentence Case

---

src/io/github/sspanak/tt9/ime/TraditionalT9.java

Problem:
As previously asked, there did not seem to be a method to handle the keyboard's main view from not showing. I have tested this method for my Sonim (which runs Android 8.1 and could not take advantage of requestShowSelf) and it is working now.
Solution:
Call showWindow(), which makes a call to showWindowInner() with the boolean you pass. When you pass true, attributes such as mShowInputRequested and mWindowVisible become true, which help assist in functions like updateInputViewShown()

added workaround to show the window for older Android devices < 9

---

src/io/github/sspanak/tt9/ime/helpers/TextField.java

Problem:
When typing a new text message and in the "To" box using OK to select a suggested contact name, I noticed the app was not handling an Action ID of 6 (IME_ACTION_DONE).
Solution:
By adding code for this Action ID, this now allows the Center/OK key to select a contact properly from the drop-down.

added DONE to allow selecting suggested names in messaging

---

src/io/github/sspanak/tt9/ime/KeyPadHandler.java

Problem:
When testing on a consumer cellular link ii where the clear key also doubles as the back key:
I was not able to back out of a text conversation because I would be on a textbox which calls for the keypad and isBackspaceHandled was always returning true here. It wasn't returning true because of onBackspace() but because the keyCode was 67 (KeyEvent.KEYCODE_DEL) and was returning true for the second part of the OR statement.
Solution:
Removed second part of conditional. onBackspace() already checks whether there's text or if it's in passthrough. Open to discussing the logic here, but it doesn't seem necessary to have this OR statement.

removed the last of the legacy Backspace hack

---

src/io/github/sspanak/tt9/ime/helpers/InputType.java
src/io/github/sspanak/tt9/ime/helpers/TextField.java
src/io/github/sspanak/tt9/ime/modes/ModePassthrough.java

Problem: When using the Calculator app, the status bar was showing and covering part of the UI. I felt it made more sense to use passthrough here, similar to the dialer. It also allows me to press * and insert a decimal point on the calculator app
Solution: in isDialer() function, also consider when the inputType is android.text.InputType.TYPE_CLASS_NUMBER

added OR operator for calculator app

---

src/io/github/sspanak/tt9/ime/TraditionalT9.java

Since we are now forcing the view on number presses, I removed the logic to force show on OK. I think this is a more user-friendly experience, as the user would be able to use the D-Pad & OK key for system functions, but if they intend to type, they can press a number key and the UI would show.
This has turned out nicely for my Contacts screen, which has a search bar on top and some contacts to scroll/select on the bottom. I can now use OK to select a contact on first press of OK instead of it initializing the keyboard UI.
Before:
After:
Secondly, I added logic to call acceptCurrentSuggestion only when the suggestion bar is showing.

changed logic to not force show on OK

---

src/io/github/sspanak/tt9/ime/TraditionalT9.java

Found some duplicate tasks
1. onKeyAddWord: calling textField.finishComposingText() and clearSuggestions(), but in clearSuggestions(), textField.finishComposingText() is called too
2. onKeyNextLanguage: commitCurrentSuggestion() is called which also runs the same tasks as clearSuggestions, and then clearSuggestions() is being called after that. I am sure there is some re-factoring of this logic that can be done, but for now just focusing on removing duplicate tasks

fixed duplicate tasks

---

src/io/github/sspanak/tt9/ime/KeyPadHandler.java

Problem:
On my QIN F21 Pro, which has a very fast processor for this application, I was noticing that at times when I press backspace/back (one button with both functions), the execution of a backspace was sometimes skipped and instead was being processed as back depending on how fast I was typing.
For instance, if I rapidly alternate presses between another number and backspace, it would immediately register "back" and I would get a popup on my screen (are you sure you'd like to discard this message?).
I did some debugging of onKeyDown and onKeyUp and found that in some instances, isBackspaceHandled was false during the onKeyUp event for backspace. 
```
Key: 4 is my backspace key, Key: 10 is my 3(DEF) key
2024-02-01 14:52:46.826  4651-4651  tt9/onKeyDown           io.github.sspanak.tt9 …
```

Backspace Handling

---

app/src/main/java/io/github/sspanak/tt9/ime/TraditionalT9.java
app/src/main/java/io/github/sspanak/tt9/ime/modes/ModeABC.java
app/src/main/java/io/github/sspanak/tt9/languages/Language.java
app/src/main/java/io/github/sspanak/tt9/ui/UI.java

Closes #238
This is an updated version of #238 by @flaviozavan. There are no functional differences, only resolved conflicts with the current `master`.

Smooth language change (updated version)

---

app/src/main/java/io/github/sspanak/tt9/ime/HotkeyHandler.java
app/src/main/java/io/github/sspanak/tt9/ime/KeyPadHandler.java
app/src/main/java/io/github/sspanak/tt9/ime/helpers/AppHacks.java
app/src/main/java/io/github/sspanak/tt9/ime/helpers/Key.java
app/src/main/java/io/github/sspanak/tt9/ime/helpers/TextField.java

~~Tries to deal with #393, #365, #423, #475~~ It didn't work, unfortunately, but at the improvements are nice to have.

Improved OK/Enter key handling

---

app/languages/definitions/Hungarian.yml
app/src/main/java/io/github/sspanak/tt9/ui/main/keys/SoftNumberKey.java
docs/dictionaries/huWordlistReadme.txt

Not sure if this is the best source for words, but I needed something to be able to text faster on my dumb phone. I've been using it for the past week and it works great for me (I did have to clean up the word list a little bit to build an APK, so it's not the exact same one as the source).
Note that I've added letters with special characters in between the normal letters, e.g. `aábc`. This is intentional as it's how I remember old dumb phones working with the Hungarian alphabet and it's logical since we use a lot of these letters.

Add Hungarian dictionary

---

README.md
app/src/main/java/io/github/sspanak/tt9/db/DataStore.java
app/src/main/java/io/github/sspanak/tt9/db/sqlite/ReadOps.java
app/src/main/java/io/github/sspanak/tt9/db/words/WordStore.java
app/src/main/java/io/github/sspanak/tt9/ime/helpers/TextField.java
app/src/main/java/io/github/sspanak/tt9/preferences/screens/hotkeys/SectionKeymap.java
app/src/main/java/io/github/sspanak/tt9/preferences/screens/main/ItemDonate.java
app/src/main/java/io/github/sspanak/tt9/preferences/screens/main/MainSettingsScreen.java
app/src/main/java/io/github/sspanak/tt9/preferences/settings/SettingsStore.java
app/src/main/java/io/github/sspanak/tt9/ui/main/keys/SoftKey.java
app/src/main/java/io/github/sspanak/tt9/ui/main/keys/SoftKeyBackspace.java
app/src/main/java/io/github/sspanak/tt9/ui/main/keys/SoftKeyLF4.java
app/src/main/java/io/github/sspanak/tt9/ui/main/keys/SwipeableKey.java
app/src/main/java/io/github/sspanak/tt9/util/Text.java
app/src/main/res/values/dimens.xml
app/src/main/res/xml/prefs.xml

Completely redone the whitespace/word boundary detection, to prevent unexpected behavior related to #333.

Small fixes 40.3

---

app/src/main/java/io/github/sspanak/tt9/hacks/DeviceInfo.java
app/src/main/java/io/github/sspanak/tt9/preferences/screens/appearance/AppearanceScreen.java
app/src/main/java/io/github/sspanak/tt9/preferences/screens/appearance/ItemNumpadWidth.java
app/src/main/java/io/github/sspanak/tt9/preferences/settings/SettingsUI.java
app/src/main/java/io/github/sspanak/tt9/ui/main/MainLayoutNumpad.java
app/src/main/res/layout/main_numpad.xml
app/src/main/res/values-bg/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-iw/strings.xml
app/src/main/res/values-lt/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-tr/strings.xml
app/src/main/res/values-uk/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/prefs_screen_appearance.xml

Configurable width
