README.md
docs/user-manual.md
src/io/github/sspanak/traditionalt9/TraditionalT9.java
src/io/github/sspanak/traditionalt9/Utils.java

"Back" can now delete text / Nokia style :)

---

src/io/github/sspanak/tt9/TraditionalT9.java

More code cleanup

---

res/values-de/strings.xml
res/values-fr/strings.xml
res/values-it/strings.xml
res/values-uk/strings.xml
src/io/github/sspanak/tt9/db/DictionaryDb.java
src/io/github/sspanak/tt9/ime/InputFieldHelper.java
src/io/github/sspanak/tt9/ime/InputModeValidator.java
src/io/github/sspanak/tt9/ime/KeyPadHandler.java
src/io/github/sspanak/tt9/ime/SoftKeyHandler.java
src/io/github/sspanak/tt9/ime/TraditionalT9.java
src/io/github/sspanak/tt9/ime/modes/InputMode.java
src/io/github/sspanak/tt9/ime/modes/Mode123.java
src/io/github/sspanak/tt9/ime/modes/ModeABC.java
src/io/github/sspanak/tt9/ime/modes/ModePredictive.java
src/io/github/sspanak/tt9/languages/Language.java
src/io/github/sspanak/tt9/preferences/T9Preferences.java
src/io/github/sspanak/tt9/settings_legacy/SettingMultiList.java
src/io/github/sspanak/tt9/ui/AddWordAct.java
src/io/github/sspanak/tt9/ui/CandidateView.java
src/io/github/sspanak/tt9/ui/TraditionalT9Settings.java
src/io/github/sspanak/tt9/ui/UI.java

Each mode is in its own class

---

README.md
docs/user-manual.md
src/io/github/sspanak/tt9/db/DictionaryDb.java
src/io/github/sspanak/tt9/db/WordsDao.java
src/io/github/sspanak/tt9/ime/KeyPadHandler.java
src/io/github/sspanak/tt9/ime/TraditionalT9.java
src/io/github/sspanak/tt9/ime/modes/InputMode.java
src/io/github/sspanak/tt9/ime/modes/Mode123.java
src/io/github/sspanak/tt9/ime/modes/ModeABC.java
src/io/github/sspanak/tt9/ime/modes/ModePredictive.java
src/io/github/sspanak/tt9/languages/Punctuation.java

Fixes #60 
Closes #68 
Closes #51 
Closes #77 
Closes #11 
Closes #69

Old-skool experience

---

docs/user-manual.md
src/io/github/sspanak/tt9/ime/KeyPadHandler.java
src/io/github/sspanak/tt9/ime/TraditionalT9.java
src/io/github/sspanak/tt9/ime/modes/InputMode.java
src/io/github/sspanak/tt9/ime/modes/ModePredictive.java
src/io/github/sspanak/tt9/ui/CandidateView.java

This is how #68 should have been implemented in the first place.
Fixes #87

More predictive mode improvements

---

assets/en-utf8.txt
src/io/github/sspanak/tt9/ime/InputModeValidator.java
src/io/github/sspanak/tt9/ime/TraditionalT9.java
src/io/github/sspanak/tt9/ime/modes/InputMode.java
src/io/github/sspanak/tt9/ime/modes/ModeABC.java
src/io/github/sspanak/tt9/ime/modes/ModePredictive.java
src/io/github/sspanak/tt9/languages/Language.java
src/io/github/sspanak/tt9/languages/definitions/Bulgarian.java
src/io/github/sspanak/tt9/languages/definitions/Dutch.java
src/io/github/sspanak/tt9/languages/definitions/English.java
src/io/github/sspanak/tt9/languages/definitions/French.java
src/io/github/sspanak/tt9/languages/definitions/German.java
src/io/github/sspanak/tt9/languages/definitions/Italian.java
src/io/github/sspanak/tt9/languages/definitions/Russian.java
src/io/github/sspanak/tt9/languages/definitions/Ukrainian.java
src/io/github/sspanak/tt9/ui/CandidateView.java
src/io/github/sspanak/tt9/ui/UI.java

Fixes #86 
Fixes #91 
Fixes #95

Suggestion improvements

---

res/layout/mainview.xml
res/layout/suggestion_list_view.xml
res/values/strings.xml
src/io/github/sspanak/tt9/ime/SoftKeyHandler.java
src/io/github/sspanak/tt9/ui/SuggestionsAdapter.java
src/io/github/sspanak/tt9/ui/SuggestionsView.java

This is my rewrite of the candidate view. However, I cannot seem to figure out how to highlight the candidate word after `scrollToPosition`. Also, this does not contain any onclicklisteners in the candidatebar, which could be implemented. But I am not sure how.

Rewrite candidate view

---

res/layout/mainview.xml
res/values/dimens.xml
src/io/github/sspanak/tt9/ime/TraditionalT9.java
src/io/github/sspanak/tt9/ime/modes/ModeABC.java

Random bugs again

---

AndroidManifest.xml
build.gradle
docs/user-manual.md
res/values-bg/strings.xml
res/values-de/strings.xml
res/values-fr/strings.xml
res/values-it/strings.xml
res/values-nl/strings.xml
res/values-ru/strings.xml
res/values-uk/strings.xml
res/values/strings.xml
res/xml/prefs.xml
src/io/github/sspanak/tt9/db/DictionaryLoader.java
src/io/github/sspanak/tt9/ime/InputFieldHelper.java
src/io/github/sspanak/tt9/ime/KeyPadHandler.java
src/io/github/sspanak/tt9/ime/TraditionalT9.java
src/io/github/sspanak/tt9/ime/modes/InputMode.java
src/io/github/sspanak/tt9/ime/modes/Mode123.java
src/io/github/sspanak/tt9/ime/modes/ModeABC.java
src/io/github/sspanak/tt9/ime/modes/ModePredictive.java
src/io/github/sspanak/tt9/languages/InvalidLanguageCharactersException.java
src/io/github/sspanak/tt9/languages/Punctuation.java
src/io/github/sspanak/tt9/preferences/SettingsStore.java
src/io/github/sspanak/tt9/ui/SuggestionsView.java

Closes https://github.com/sspanak/tt9/issues/113
Closes https://github.com/sspanak/tt9/issues/102
Closes #78 
Fixes #125 
Additionally, made the automatic capitalization a setting.

Zero improvements

---

src/io/github/sspanak/tt9/ime/KeyPadHandler.java
src/io/github/sspanak/tt9/ime/SoftKeyHandler.java
src/io/github/sspanak/tt9/ime/TraditionalT9.java

Fixes #123. 
~~Preferably merge after #122 to avoid potential conflicts.~~

No more unnecessary throtling of the hardware backspace key

---

src/io/github/sspanak/tt9/ime/InputFieldHelper.java
src/io/github/sspanak/tt9/ime/KeyPadHandler.java
src/io/github/sspanak/tt9/ime/TraditionalT9.java
src/io/github/sspanak/tt9/ime/modes/InputMode.java
src/io/github/sspanak/tt9/ime/modes/ModePredictive.java

Closes #48 
~~Merge after #122 and take care of the conflicts.~~

Text case is determined from the input field on startup

---

src/io/github/sspanak/tt9/ime/TraditionalT9.java
src/io/github/sspanak/tt9/ime/modes/InputMode.java
src/io/github/sspanak/tt9/ime/modes/ModePredictive.java

Manual text case change is confusing

---

res/values-bg/strings.xml
res/values-fr/strings.xml
res/values/strings.xml
src/io/github/sspanak/tt9/db/DictionaryDb.java
src/io/github/sspanak/tt9/db/WordsDao.java
src/io/github/sspanak/tt9/ime/EmptyDatabaseWarning.java
src/io/github/sspanak/tt9/ime/modes/ModePredictive.java
src/io/github/sspanak/tt9/preferences/SettingsStore.java

Warning message when there is no dictionary

---

src/io/github/sspanak/tt9/ime/SoftKeyHandler.java
src/io/github/sspanak/tt9/ime/TraditionalT9.java
src/io/github/sspanak/tt9/preferences/SettingsStore.java

Fixed typing bugs

---

src/io/github/sspanak/tt9/ime/KeyPadHandler.java

Back is not working

---

CONTRIBUTING.md
README.md
src/io/github/sspanak/tt9/db/DictionaryDb.java
src/io/github/sspanak/tt9/db/WordsDao.java
src/io/github/sspanak/tt9/ime/TraditionalT9.java
src/io/github/sspanak/tt9/languages/Punctuation.java
src/io/github/sspanak/tt9/preferences/PreferencesActivity.java
src/io/github/sspanak/tt9/preferences/SettingsStore.java

Fixes #161 
Fixes #162 
Fixes #160

Fixed word frequency issues causing wrong suggestions order

---

docs/user-manual.md

Add 2 additional methods to reach the settings screen as suggested by @sspanak

Update user-manual.md - Settings Screen

---

CONTRIBUTING.md
docs/user-manual.md
res/values-bg/strings.xml
res/values-es/strings.xml
res/values-fr/strings.xml
res/values-it/strings.xml
res/values-ru/strings.xml
res/values-uk/strings.xml
res/values/strings.xml
res/xml/prefs.xml
src/io/github/sspanak/tt9/ime/KeyPadHandler.java
src/io/github/sspanak/tt9/ime/TraditionalT9.java
src/io/github/sspanak/tt9/ime/helpers/InputFieldHelper.java
src/io/github/sspanak/tt9/ime/helpers/InputModeValidator.java
src/io/github/sspanak/tt9/ime/helpers/Key.java
src/io/github/sspanak/tt9/ime/helpers/TextHelper.java
src/io/github/sspanak/tt9/ime/modes/InputMode.java
src/io/github/sspanak/tt9/ime/modes/ModePredictive.java
src/io/github/sspanak/tt9/languages/Characters.java
src/io/github/sspanak/tt9/languages/Punctuation.java
src/io/github/sspanak/tt9/languages/definitions/Bulgarian.java
src/io/github/sspanak/tt9/languages/definitions/English.java
src/io/github/sspanak/tt9/languages/definitions/Russian.java
src/io/github/sspanak/tt9/languages/definitions/Spanish.java
src/io/github/sspanak/tt9/languages/definitions/Ukrainian.java
src/io/github/sspanak/tt9/preferences/SettingsStore.java
src/io/github/sspanak/tt9/preferences/helpers/Hotkeys.java
src/io/github/sspanak/tt9/preferences/items/ItemSelectZeroKeyCharacter.java
src/io/github/sspanak/tt9/preferences/items/SectionKeymap.java
src/io/github/sspanak/tt9/ui/SuggestionsView.java

Fixes #169
Fixes #151
Fixes #168
Fixes #176 
Fixes #173

Random bugs 17

---

docs/user-manual.md
src/io/github/sspanak/tt9/ime/TraditionalT9.java
src/io/github/sspanak/tt9/ime/helpers/TextField.java

OK sends messages

---

AndroidManifest.xml
README.md
docs/user-manual.md
res/values-bg/strings.xml
res/values-de/strings.xml
res/values-es/strings.xml
res/values-fr/strings.xml
res/values-it/strings.xml
res/values-nl/strings.xml
res/values-pt-rBR/strings.xml
res/values-ru/strings.xml
res/values-uk/strings.xml
res/values/strings.xml
res/xml/prefs_screen_setup.xml
src/io/github/sspanak/tt9/ime/helpers/GlobalKeyboardSettings.java
src/io/github/sspanak/tt9/preferences/PreferencesActivity.java
src/io/github/sspanak/tt9/preferences/items/ItemSelectGlobalKeyboard.java
src/io/github/sspanak/tt9/preferences/items/ItemSetDefaultGlobalKeyboard.java
src/io/github/sspanak/tt9/preferences/screens/SetupScreen.java

Initial setup screen

---

res/values/strings.xml
src/io/github/sspanak/tt9/preferences/helpers/Hotkeys.java

Something was wrong with #214 and #215, so I created a new branch and merged them together.

Add soft key support

---

src/io/github/sspanak/tt9/ime/KeyPadHandler.java
src/io/github/sspanak/tt9/ime/TraditionalT9.java

Attempt to fix OK again

---

src/io/github/sspanak/tt9/ime/TraditionalT9.java

Do not force show the main view on start up

---

.editorconfig
res/layout/addwordview.xml
res/layout/main_numpad.xml
res/layout/main_small.xml
res/layout/suggestion_list.xml
res/layout/suggestion_list_numpad.xml
res/values-bg/strings.xml
res/values-es/strings.xml
res/values-fr/strings.xml
res/values-it/strings.xml
res/values-ru/strings.xml
res/values-uk/strings.xml
res/values/strings.xml
src/io/github/sspanak/tt9/db/DictionaryLoader.java
src/io/github/sspanak/tt9/db/exceptions/DictionaryImportException.java
src/io/github/sspanak/tt9/ime/KeyPadHandler.java
src/io/github/sspanak/tt9/ime/TraditionalT9.java
src/io/github/sspanak/tt9/ime/helpers/TextField.java
src/io/github/sspanak/tt9/languages/InvalidLanguageCharactersException.java
src/io/github/sspanak/tt9/languages/definitions/Spanish.java
src/io/github/sspanak/tt9/preferences/SettingsStore.java
src/io/github/sspanak/tt9/preferences/items/ItemSelectLanguage.java

(not so) big code cleanup

---

res/values/strings.xml
src/io/github/sspanak/tt9/preferences/items/ItemSelectZeroKeyCharacter.java

added ',' to the 0-key double press shortcut list

---

src/io/github/sspanak/tt9/db/DictionaryLoader.java

Simplified logic to use the included optional boolean of includeDigit. This way we do not have to check for it in the if statement.

remove logic for numbers, instead using includeDigit

---

docs/user-manual.md
res/values-bg/strings.xml
res/values-fr/strings.xml
res/values-nl/strings.xml
res/values-ru/strings.xml
res/values-uk/strings.xml
res/values/strings.xml
src/io/github/sspanak/tt9/db/DictionaryDb.java
src/io/github/sspanak/tt9/db/DictionaryLoader.java
src/io/github/sspanak/tt9/db/migrations/DB10.java
src/io/github/sspanak/tt9/db/room/TT9Room.java
src/io/github/sspanak/tt9/db/room/WordList.java
src/io/github/sspanak/tt9/db/room/WordsDao.java
src/io/github/sspanak/tt9/preferences/items/ItemClickable.java
src/io/github/sspanak/tt9/preferences/items/ItemLoadDictionary.java
src/io/github/sspanak/tt9/preferences/items/ItemTruncateAll.java
src/io/github/sspanak/tt9/preferences/items/ItemTruncateUnselected.java
src/io/github/sspanak/tt9/preferences/screens/DictionariesScreen.java
src/io/github/sspanak/tt9/ui/DictionaryLoadingBar.java

Improved db operations feedback

---

docs/user-manual.md
src/io/github/sspanak/tt9/ime/TraditionalT9.java
src/io/github/sspanak/tt9/preferences/PreferencesActivity.java
src/io/github/sspanak/tt9/preferences/SettingsStore.java
src/io/github/sspanak/tt9/preferences/helpers/Hotkeys.java
src/io/github/sspanak/tt9/preferences/items/SectionKeymap.java

Hotkey configuration issues

---

res/layout/main_numpad.xml
res/values-bg/strings.xml
res/values-fr/strings.xml
res/values-ru/strings.xml
res/values-uk/strings.xml
res/values/dimens.xml
res/values/strings.xml
res/values/styles.xml
res/xml/prefs_screen_hotkeys.xml
src/io/github/sspanak/tt9/ime/KeyPadHandler.java
src/io/github/sspanak/tt9/ime/TraditionalT9.java
src/io/github/sspanak/tt9/preferences/SettingsStore.java
src/io/github/sspanak/tt9/preferences/helpers/Hotkeys.java
src/io/github/sspanak/tt9/preferences/items/SectionKeymap.java
src/io/github/sspanak/tt9/preferences/screens/HotkeysScreen.java
src/io/github/sspanak/tt9/ui/main/MainLayoutNumpad.java
src/io/github/sspanak/tt9/ui/main/keys/SoftKey.java

Arrows improvement

---

src/io/github/sspanak/tt9/ime/TraditionalT9.java

The composing/selected text is no longer cleared on startup

---

src/io/github/sspanak/tt9/ime/KeyPadHandler.java
src/io/github/sspanak/tt9/ime/TraditionalT9.java
src/io/github/sspanak/tt9/ime/helpers/Key.java
src/io/github/sspanak/tt9/ime/modes/InputMode.java
src/io/github/sspanak/tt9/ime/modes/Mode123.java
src/io/github/sspanak/tt9/ime/modes/ModeABC.java
src/io/github/sspanak/tt9/ime/modes/ModePassthrough.java
src/io/github/sspanak/tt9/ime/modes/ModePredictive.java
src/io/github/sspanak/tt9/ui/main/keys/SoftPunctuationKey.java

Cross fingers this is the fix for: ~~#300~~, #290 and #241.
EDIT: It does not fix #300 :cry:

Mode refactoring again

---

res/layout/addwordview.xml
res/values-bg/strings.xml
res/values-de/strings.xml
res/values-es/strings.xml
res/values-fr/strings.xml
res/values-it/strings.xml
res/values-iw/strings.xml
res/values-nl/strings.xml
res/values-pt-rBR/strings.xml
res/values-ru/strings.xml
res/values-uk/strings.xml
res/values/strings.xml
src/io/github/sspanak/tt9/db/DictionaryDb.java
src/io/github/sspanak/tt9/ime/TraditionalT9.java
src/io/github/sspanak/tt9/ime/helpers/TextField.java
src/io/github/sspanak/tt9/preferences/SettingsStore.java
src/io/github/sspanak/tt9/ui/AddWordAct.java

Simpler word adding

---

res/values-bg/strings.xml
res/values-fr/strings.xml
res/values-ru/strings.xml
res/values-uk/strings.xml
res/values/strings.xml
src/io/github/sspanak/tt9/ime/KeyPadHandler.java
src/io/github/sspanak/tt9/ime/TraditionalT9.java
src/io/github/sspanak/tt9/ime/helpers/AppHacks.java
src/io/github/sspanak/tt9/ime/modes/InputMode.java
src/io/github/sspanak/tt9/ime/modes/ModePredictive.java
src/io/github/sspanak/tt9/ime/modes/helpers/AutoTextCase.java

Closes #367: the MainView is visible in dropdowns or other non-text inputs
Fixed logging settings not being applied at startup sometimes
Closes #364: removed isActive
Fixes #385, Fixes #389: fixed a startup crash in onEvaluateInputViewShown()

Summer bugs

---

src/io/github/sspanak/tt9/ime/KeyPadHandler.java

Problem:
Just noticed an inefficiency in the code, calling isNumber multiple times in onKeyDown and in onKeyLongPress
Solution:
Reworked code as needed

Remove redundant calls to isNumber

---

src/io/github/sspanak/tt9/ime/TraditionalT9.java
src/io/github/sspanak/tt9/ime/helpers/TextField.java
src/io/github/sspanak/tt9/ime/modes/InputMode.java
src/io/github/sspanak/tt9/ime/modes/ModePredictive.java
src/io/github/sspanak/tt9/ime/modes/helpers/AutoTextCase.java
src/io/github/sspanak/tt9/ime/modes/helpers/Predictions.java
src/io/github/sspanak/tt9/languages/Language.java

small fixes 27

---

languages/dictionaries/de-utf8.csv
languages/dictionaries/en-utf8.csv
languages/dictionaries/fi-utf8.csv
languages/dictionaries/nb-utf8.csv

More dictionary fixes (hopefully that's final)

---

res/layout/main_numpad.xml
src/io/github/sspanak/tt9/languages/Characters.java
src/io/github/sspanak/tt9/languages/Language.java
src/io/github/sspanak/tt9/ui/main/keys/SoftBackspaceKey.java
src/io/github/sspanak/tt9/ui/main/keys/SoftKey.java
src/io/github/sspanak/tt9/ui/main/keys/SoftNumberKey.java

RTL language improvements

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/github/sspanak/tt9/ime/TraditionalT9.java
app/src/main/java/io/github/sspanak/tt9/ime/modes/InputMode.java
app/src/main/java/io/github/sspanak/tt9/ime/modes/Mode123.java
app/src/main/java/io/github/sspanak/tt9/ime/modes/ModePredictive.java

* fixed issues with switching the text case
* fixed not possible to type currency characters in RTL languages

fixed character case switching issues

---

app/src/main/java/io/github/sspanak/tt9/db/DictionaryLoader.java
app/src/main/java/io/github/sspanak/tt9/db/WordStore.java
app/src/main/java/io/github/sspanak/tt9/db/sqlite/SQLiteOpener.java
app/src/main/java/io/github/sspanak/tt9/ime/TraditionalT9.java
app/src/main/java/io/github/sspanak/tt9/ime/helpers/TextField.java
app/src/main/java/io/github/sspanak/tt9/ime/modes/InputMode.java
app/src/main/java/io/github/sspanak/tt9/ime/modes/ModePredictive.java
app/src/main/java/io/github/sspanak/tt9/ime/modes/helpers/Predictions.java
app/src/main/java/io/github/sspanak/tt9/languages/Characters.java
app/src/main/java/io/github/sspanak/tt9/languages/EmojiLanguage.java
app/src/main/java/io/github/sspanak/tt9/languages/Language.java
docs/user-manual.md

Adding emoji

---

README.md

tt9 is on F-Droid finally! :tada: 
closes #382

Add F-Droid link

---

app/languages/definitions/Croatian.yml
docs/dictionaries/hrWordListReadme.txt

Dictionary taken from Openboard and cleaned up from non-Croatian words.

Add Croatian language and dictionary

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/io/github/sspanak/tt9/db/exporter/AbstractExporter.java
app/src/main/java/io/github/sspanak/tt9/ime/TraditionalT9.java
app/src/main/java/io/github/sspanak/tt9/ime/modes/ModePredictive.java
app/src/main/java/io/github/sspanak/tt9/preferences/screens/languages/ItemDictionaryNotifications.java
app/src/main/java/io/github/sspanak/tt9/preferences/screens/languages/LanguagesScreen.java
app/src/main/java/io/github/sspanak/tt9/preferences/screens/setup/ItemSelectGlobalKeyboard.java
app/src/main/java/io/github/sspanak/tt9/ui/UI.java
app/src/main/java/io/github/sspanak/tt9/ui/dialogs/AddWordDialog.java
app/src/main/java/io/github/sspanak/tt9/util/Permissions.java
app/src/main/res/values-bg/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-iw/strings.xml
app/src/main/res/values-lt/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-uk/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/prefs_screen_languages.xml
docs/user-manual.md
gradle.properties

TODO:
- ~~update the readme about Android 13 notification permissions~~
- ~~translate the notifications preferences~~
- ~~add Android 14 support~~

Add Android 14 support

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

* upgraded com.android.application 8.4.2 -> 8.5.0
* upgraded gradle 8.6 -> 8.7

dependencies update

---

app/build.gradle
app/constants.gradle
app/help-tools.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/io/github/sspanak/tt9/preferences/HelpActivity.java
app/src/main/java/io/github/sspanak/tt9/preferences/screens/main/MainSettingsScreen.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/prefs.xml
docs/user-manual.md

Real help screen

---

app/src/main/java/io/github/sspanak/tt9/ime/TypingHandler.java
app/src/main/java/io/github/sspanak/tt9/ime/helpers/TextField.java
app/src/main/java/io/github/sspanak/tt9/ime/modes/InputMode.java
app/src/main/java/io/github/sspanak/tt9/ime/modes/ModePredictive.java
app/src/main/java/io/github/sspanak/tt9/preferences/settings/SettingsTyping.java
app/src/main/java/io/github/sspanak/tt9/util/Text.java
app/src/main/res/values-bg/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-iw/strings.xml
app/src/main/res/values-lt/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-tr/strings.xml
app/src/main/res/values-uk/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/prefs_screen_keypad.xml

- ~~must preserve the text case~~
- ~~add a settings to control it~~
- ~~Bug~~
1. ~~Go to text editing~~
2. ~~Press Backspace to edit a word~~
3. ~~Press 0-key/space. This erases the current suggestion, instead of accepting it.~~
- ~~translations~~

Recomposing

---

scripts/extract-frequencies-from-text.js
scripts/validate-devanagari.js

* a script for injesting words by unicode range
* Devanagari validation script

new word processing scripts

---

app/src/main/java/io/github/sspanak/tt9/ime/TextEditingHandler.java
app/src/main/java/io/github/sspanak/tt9/preferences/settings/SettingsUI.java
app/src/main/java/io/github/sspanak/tt9/ui/main/BaseMainLayout.java
app/src/main/java/io/github/sspanak/tt9/ui/main/MainLayoutNumpad.java
app/src/main/java/io/github/sspanak/tt9/ui/main/keys/SoftKeyBackspace.java
app/src/main/java/io/github/sspanak/tt9/ui/main/keys/SoftKeyNumber0.java
app/src/main/java/io/github/sspanak/tt9/ui/main/keys/SoftKeyNumber0Long.java
app/src/main/java/io/github/sspanak/tt9/ui/main/keys/SoftKeyOk.java
app/src/main/java/io/github/sspanak/tt9/ui/main/keys/SoftKeyPunctuation.java
app/src/main/java/io/github/sspanak/tt9/ui/main/keys/SoftKeyPunctuationShort.java
app/src/main/java/io/github/sspanak/tt9/ui/main/keys/SoftKeyRF3.java
app/src/main/res/layout/key_overlay_hold_text.xml
app/src/main/res/layout/main_numpad.xml
app/src/main/res/layout/panel_long_spacebar.xml
app/src/main/res/layout/panel_numpad_right.xml
app/src/main/res/values-bg/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-iw/strings.xml
app/src/main/res/values-lt/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-tr/strings.xml
app/src/main/res/values-uk/strings.xml
app/src/main/res/values/styles.xml

Addresses more of the requests in #700 and fixes small regressions during the latest feature development.

Long spacebar + visual enhancements

---

app/languages/definitions/Slovenian.yml
app/languages/dictionaries/sl-utf8.csv
docs/dictionaries/slWordlistReadme.txt

Add Slovenian language support

---

app/src/main/java/io/github/sspanak/tt9/ui/main/MainLayoutTray.java
app/src/main/res/values/dimens.xml
app/src/main/res/values/styles.xml
build.gradle

Fix oversized words
